apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argo-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JonathanYogev/argocd-gitOps-repo.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.dev.yaml
  destination:
    server: https://2D936A0BF30A77AEFF2ECACF24680DF0.sk1.il-central-1.eks.amazonaws.com
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true